# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 21:16
from __future__ import unicode_literals
from datetime import date

from django.db import migrations, models


def datetime_to_date(apps, schema_editor):
    Menu = apps.get_model('menu', 'menu')
    for menu in Menu.objects.all():
        if menu.expiration_date:
            menu.e_date = menu.expiration_date.date()
        else:
            menu.e_date = None
        menu.save()


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20170131_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='e_date',
            field=models.DateField(blank=True, null=True),
            preserve_default=True,
        ),
        migrations.RunPython(datetime_to_date),
        migrations.RemoveField(
            model_name='menu',
            name='expiration_date'
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='e_date',
            new_name='expiration_date'
        ),
    ]
