# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20170131_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['expiration_date']},
        ),
    ]
