# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20170131_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(to='menu.Item'),
        ),
    ]
