# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 21:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20170201_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='last_modified',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
